repos:
- repo: local
  hooks:
    - id: ruff-linter
      name: ruff linter
      entry: ruff check
      args: [--fix, --config=pyproject.toml]
      language: system
      types: [python]
      stages: [pre-commit]

    - id: ruff-formatter
      name: ruff formatter
      entry: ruff format
      args: [--config=pyproject.toml]
      language: system
      types: [python]
      stages: [pre-commit]



